import { createTheme } from '@vanilla-extract/css';
import { colors } from '../tokens.css';
import { base } from './globalTokens.css';
import { themeTokens } from './theme-contract.css';

export const bccLightThemeClass = createTheme(themeTokens, {
  ...base,
  themeColors: {
    neutral: {
      100: colors.neutral100,
      90: colors.neutral90,
      80: colors.neutral80,
      70: colors.neutral70,
      60: colors.neutral60,
      50: colors.neutral50,
      40: colors.neutral40,
      30: colors.neutral30,
      20: colors.neutral20,
      10: colors.neutral10,
    },
    primary: {
      lighter: colors.teal10,
      light: colors.teal30,
      base: colors.teal50,
      dark: colors.teal70,
      darker: colors.teal90,
    },
    secondary: {
      lighter: colors.neutral10,
      light: colors.neutral20,
      base: colors.neutral40,
      dark: colors.neutral60,
      darker: colors.neutral80,
    },
    tertiary: {
      lighter: colors.blue10,
      light: colors.blue30,
      base: colors.blue50,
      dark: colors.blue70,
      darker: colors.blue90,
    },
    accent: {
      lighter: colors.purple10,
      light: colors.purple30,
      base: colors.purple50,
      dark: colors.purple70,
      darker: colors.purple90,
    },
    help: {
      lighter: colors.magenta10,
      light: colors.magenta30,
      base: colors.magenta50,
      dark: colors.magenta70,
      darker: colors.magenta90,
    },
    info: {
      lighter: colors.blue10,
      light: colors.blue30,
      base: colors.blue50,
      dark: colors.blue70,
      darker: colors.blue90,
    },
    success: {
      lighter: colors.green10,
      light: colors.green30,
      base: colors.green50,
      dark: colors.green70,
      darker: colors.green90,
    },
    warning: {
      lighter: colors.yellow10,
      light: colors.yellow30,
      base: colors.yellow50,
      dark: colors.yellow70,
      darker: colors.yellow90,
    },
    error: {
      lighter: colors.red10,
      light: colors.red30,
      base: colors.red50,
      dark: colors.red70,
      darker: colors.red90,
    },
    foreground: colors.white,
    background: {
      body: colors.gray,
      primary: colors.teal10,
      secondary: colors.neutral10,
      tertiary: colors.blue10,
      accent: colors.purple10,
      info: colors.blue10,
      help: colors.magenta10,
      success: colors.green10,
      warning: colors.yellow10,
      error: colors.red10,
    },
    border: {
      default: colors.neutral20,
      primary: colors.teal50,
      secondary: colors.neutral40,
      tertiary: colors.blue50,
      accent: colors.purple50,
      info: colors.blue50,
      help: colors.magenta50,
      success: colors.green50,
      warning: colors.yellow50,
      error: colors.red50,
    },
    feedback: {
      info: colors.blue50,
      help: colors.magenta50,
      success: colors.green50,
      warning: colors.yellow50,
      error: colors.red50,
    },
    text: {
      default: colors.neutral100,
      muted: colors.neutral20,
      primary: colors.teal50,
      secondary: colors.neutral40,
      tertiary: colors.blue50,
    },
    interaction: {
      disabled: colors.neutral30,
      active: colors.teal60,
      inactive: colors.neutral60,
      selected: colors.blue50,
      hover: colors.blue30,
    },
  },
});

export const bccDarkThemeClass = createTheme(themeTokens, {
  ...base,
  themeColors: {
    neutral: {
      100: colors.neutral100,
      90: colors.neutral90,
      80: colors.neutral80,
      70: colors.neutral70,
      60: colors.neutral60,
      50: colors.neutral50,
      40: colors.neutral40,
      30: colors.neutral30,
      20: colors.neutral20,
      10: colors.neutral10,
    },
    primary: {
      lighter: colors.teal10,
      light: colors.teal30,
      base: colors.teal50,
      dark: colors.teal70,
      darker: colors.teal90,
    },
    secondary: {
      lighter: colors.neutral10,
      light: colors.neutral20,
      base: colors.neutral40,
      dark: colors.neutral60,
      darker: colors.neutral80,
    },
    tertiary: {
      lighter: colors.blue10,
      light: colors.blue30,
      base: colors.blue50,
      dark: colors.blue70,
      darker: colors.blue90,
    },
    accent: {
      lighter: colors.purple10,
      light: colors.purple30,
      base: colors.purple50,
      dark: colors.purple70,
      darker: colors.purple90,
    },
    help: {
      lighter: colors.magenta10,
      light: colors.magenta30,
      base: colors.magenta50,
      dark: colors.magenta70,
      darker: colors.magenta90,
    },
    info: {
      lighter: colors.blue10,
      light: colors.blue30,
      base: colors.blue50,
      dark: colors.blue70,
      darker: colors.blue90,
    },
    success: {
      lighter: colors.green10,
      light: colors.green30,
      base: colors.green50,
      dark: colors.green70,
      darker: colors.green90,
    },
    warning: {
      lighter: colors.yellow10,
      light: colors.yellow30,
      base: colors.yellow50,
      dark: colors.yellow70,
      darker: colors.yellow90,
    },
    error: {
      lighter: colors.red10,
      light: colors.red30,
      base: colors.red50,
      dark: colors.red70,
      darker: colors.red90,
    },
    foreground: colors.neutral80,
    background: {
      body: colors.neutral100,
      primary: colors.teal10,
      secondary: colors.neutral10,
      tertiary: colors.blue10,
      accent: colors.purple10,
      info: colors.blue10,
      help: colors.magenta10,
      success: colors.green10,
      warning: colors.yellow10,
      error: colors.red10,
    },
    border: {
      default: colors.neutral70,
      primary: colors.teal30,
      secondary: colors.neutral20,
      tertiary: colors.blue30,
      accent: colors.purple30,
      info: colors.blue30,
      help: colors.magenta30,
      success: colors.green30,
      warning: colors.yellow30,
      error: colors.red30,
    },
    feedback: {
      info: colors.blue30,
      help: colors.magenta30,
      success: colors.green30,
      warning: colors.yellow30,
      error: colors.red30,
    },
    text: {
      default: colors.neutral10,
      muted: colors.neutral60,
      primary: colors.teal30,
      secondary: colors.neutral20,
      tertiary: colors.blue30,
    },
    interaction: {
      disabled: colors.neutral60,
      active: colors.teal30,
      inactive: colors.neutral60,
      selected: colors.blue30,
      hover: colors.blue10,
    },
  },
});
