import { createThemeContract } from '@vanilla-extract/css';
import { base } from './globalTokens.css';

export const themeTokens = createThemeContract({
  ...base,
  themeColors: {
    neutral: {
      100: '',
      90: '',
      80: '',
      70: '',
      60: '',
      50: '',
      40: '',
      30: '',
      20: '',
      10: '',
    },
    primary: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    secondary: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    tertiary: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    accent: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    help: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    info: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    success: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    warning: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    error: {
      lighter: '',
      light: '',
      base: '',
      dark: '',
      darker: '',
    },
    foreground: '',
    background: {
      body: '',
      primary: '',
      secondary: '',
      tertiary: '',
      accent: '',
      info: '',
      help: '',
      success: '',
      warning: '',
      error: '',
    },
    border: {
      default: '',
      primary: '',
      secondary: '',
      tertiary: '',
      accent: '',
      info: '',
      help: '',
      success: '',
      warning: '',
      error: '',
    },
    feedback: {
      info: '',
      help: '',
      success: '',
      warning: '',
      error: '',
    },
    text: {
      default: '',
      muted: '',
      primary: '',
      secondary: '',
      tertiary: '',
    },
    interaction: {
      disabled: '',
      active: '',
      inactive: '',
      selected: '',
      hover: '',
    },
  },
});
